server:
  port: 10000
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: localhost:8848
    gateway:
      routes:
        - id: path_route_user
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: path_route_permission
          uri: lb://permission-service
          predicates:
            - Path=/perm/**
        - id: path_route_logging
          uri: lb://logging-service
          predicates:
            - Path=/log/**
      default-filters:
        - StripPrefix=1



knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 用户服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: user/v2/api-docs?group=default
        service-name: user-service
        context-path: /user
        order: 1
      - name: 权限服务
        url: perm/v2/api-docs?group=default
        service-name: permission-service
        # 路由前缀
        context-path: /perm
        order: 2
      - name: 日志服务
        url: log/v2/api-docs?group=default
        service-name: logging-service
        # 路由前缀
        context-path: /log
        order: 3